# Generated by Django 5.0.6 on 2024-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_custumer_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='bahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='ukuran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='unit_ukuran',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('m', 'Meters')], default='cm', max_length=2),
        ),
        migrations.AddField(
            model_name='produk',
            name='warna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
